### ISSUE TITLE
Error on upgrading plugin

### ISSUE THREAD

**Issue by marcobra** [elpaso/qgis-geocoding#12]
Hi here what i get on 
QGIS 2.8.1-Wien on Ubuntu 14.04.2 LTS

mpossibile caricare il plugin GeoCoding a causa di un errore chiamando il metodo classFactory()

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: 'module' object has no attribute 'classFactory'

Versione Python:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

Versione di QGIS:
2.8.1-Wien Wien, exported

Percorso Python: ['/home/ubuntu/.qgis2/python/plugins/GeoCoding', '/home/ubuntu/.qgis2/python/plugins/GeoCoding', '/home/ubuntu/.qgis2/python/plugins/postgis_geoprocessing', '/home/ubuntu/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/ubuntu/.qgis2/python', u'/home/ubuntu/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/csvkit-0.9.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/dbf-0.94.003-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/six-1.8.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/xlrd-0.9.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/jdcal-1.0-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/ubuntu/.qgis2//python', '/home/ubuntu/.qgis2/python/plugins/SelectTools/tools', '/home/ubuntu/.qgis2/python/plugins/mmqgis/forms', '/home/ubuntu/.qgis2/python/plugins/DataDrivenInputMask', '/home/ubuntu/.qgis2/python/plugins/HouseNumbering/forms', '/home/ubuntu/.qgis2/python/plugins/StreamFeatureExtractor/third_party', '/home/ubuntu/.qgis2/python/plugins/QuickMultiAttributeEdit/forms', '/usr/share/qgis/python/plugins/fTools/tools']

**Comment by elpaso** [comment]
Does this error pop up even if you restart QGIS or just when upgrading?

**Comment by elpaso** [comment]
Fixed, but not yet released. It's only an issue when a plugin is reloaded during upgrade or when using plugin reloader.

**Comment by marcobra** [comment]
FYI the issue is on upgrading installed plugin 
Thank
