### ISSUE TITLE
feature request: zoom in to result

### ISSUE THREAD

**Issue by rduivenvoorde** [elpaso/qgis-geocoding#2]
using the geocoder plugin in a newly opened OpenLayers project (default zoomed out to whole world), a hit with one result will show the result, but as a point on the world (like search for 'haarlem' will show you a point, in NL but not zoom in).

If I'm correct, the result of the geocoding xml of google also returns a bbox of the 'feature', or some feature type or so...

It would be a nice feature to take that into account and zoom in to the bbox of the result.

Thanks

**Comment by elpaso** [comment]
I think this is now implemented
