### ISSUE TITLE
GeoCoding plugin error on QGIS3.0 - TypeError: QgsPoint(): arguments did not match any overloaded

### ISSUE THREAD

**Issue by ozo360** [elpaso/qgis-geocoding#23]
I am running QGIS 3.0 on Windows7, I get the following error when trying to search:

An error has occurred while executing Python code:

> TypeError: QgsPoint(): arguments did not match any overloaded call:   overload 1: argument 1 has unexpected type 'str'   overload 2: argument 1 has unexpected type 'str'   overload 3: argument 1 has unexpected type 'str'   overload 4: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:/Users/account/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoCoding\GeoCoding.py", line 240, in geocode
    self.process_point(place_dlg.placesComboBox.currentText(), point)
  File "C:/Users/account/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoCoding\GeoCoding.py", line 266, in process_point
    point = QgsPoint(point[0], point[1])
TypeError: QgsPoint(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'str'
  overload 2: argument 1 has unexpected type 'str'
  overload 3: argument 1 has unexpected type 'str'
  overload 4: argument 1 has unexpected type 'str'

Perhaps I should change Line 266 to this
`point = QgsPoint(float(point[0]), float(point[1]))`

**Comment by elpaso** [comment]
Thanks for reporting this issue. Can you please change that line and see if that solve the issue?

**Comment by ozo360** [comment]
I solved it in my environment

**Comment by elpaso** [comment]
Thanks, I'll make a new version

**Comment by ozo360** [comment]
Tested with windows 10 and windows 7 and it worked fine.

**Comment by elpaso** [comment]
Thanks!

**Comment by qudratramzi** [comment]
hello dears,
unfortunatly i have the same error, but don't know how to solve it.

**Comment by qudratramzi** [comment]
An error has occurred while executing Python code: 

TypeError: QgsPointXY(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: argument 1 has unexpected type 'str'   overload 3: argument 1 has unexpected type 'str'   overload 4: argument 1 has unexpected type 'str'   overload 5: argument 1 has unexpected type 'str'   overload 6: argument 1 has unexpected type 'str'

**Comment by qudratramzi** [comment]
this is the error as i got it, can you tell me through wher i can solve it. many many thanks
