### ISSUE TITLE
Error when calling initGui() method  

### ISSUE THREAD

**Issue by arthuragone** [elpaso/qgis-geocoding#27]
Couldn't load plugin 'GeoCoding' due to an error when calling its initGui() method  
NameError: name 'inspect' is not defined 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 346, in startPlugin
    plugins[packageName].initGui()
  File "/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/GeoCoding.py", line 68, in initGui
    current_directory = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
NameError: name 'inspect' is not defined
 Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]  QGIS version: 3.2.0-Bonn Bonn, exported  
Python Path:
	•	/Applications/QGIS3.app/Contents/MacOS/../Resources/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
	•	/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools

**Comment by mirandadam** [comment]
Sorry I didn't see this before. I opened a duplicate issue as #28. Please check there for the solution.
