### ISSUE TITLE
Can not start plugin in QGis 3.2

### ISSUE THREAD

**Issue by mirandadam** [elpaso/qgis-geocoding#28]
Hi, I have just tried your plugin in QGis 3.2 and it is awesome!!! I did have to include a "import inspect" statement at the beginning of GeoCoding.py however. Pull request follows.

The error message I get is:

```
Couldn't load plugin 'GeoCoding' due to an error when calling its initGui() method 

NameError: name 'inspect' is not defined 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 346, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/miranda.dam/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoCoding\GeoCoding.py", line 68, in initGui
    current_directory = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
NameError: name 'inspect' is not defined


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.0-Bonn Bonn, bc43194061 

Python Path:
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python
C:/Users/miranda.dam/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/miranda.dam/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.2\bin\python36.zip
C:\PROGRA~1\QGIS3~1.2\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib
C:\Program Files\QGIS 3.2\bin
C:\PROGRA~1\QGIS3~1.2\apps\Python36
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\Pythonwin
C:/Users/miranda.dam/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
```

**Comment by mirandadam** [comment]
I forgot to mention:

- While the plugin is not patched, the user can make a quick fix by editing the file:
`C:\Users\youruser\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoCoding\GeoCoding.py`
Just add a line with `import inspect` right after `import sys, os` on line 20, save the file, and activate the plugin again. No QGis restart is necessary.
- I did not test this fix with previous versions of QGis. Please test this at least with the 2.18 LTS version to make sure nothing breaks.
- I did not test with the linux versions of QGis. Although I can foresee no reason why it wouldn't work, it is important to test with 3.2 and 2.18 LTS nonetheless.

Also, sorry, this is a duplicate of #27. I would rather mark #27 as the duplicate, though, because this issue references the pull request.

**Comment by elpaso** [comment]
Sorry guys: super busy days. I think `inspect` dependency should be removed from the code (IIRC it is just used to construct a path).

**Comment by arthuragone** [comment]
Same error with Mac Osx QGIS 3.2 

```
Couldn't load plugin 'GeoCoding' due to an error when calling its initGui() method  
NameError: name 'inspect' is not defined 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 346, in startPlugin
    plugins[packageName].initGui()
  File "/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/GeoCoding.py", line 68, in initGui
    current_directory = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
NameError: name 'inspect' is not defined
 Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]  QGIS version: 3.2.0-Bonn Bonn, exported  
Python Path:
	•	/Applications/QGIS3.app/Contents/MacOS/../Resources/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
	•	/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
	•	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python
	•	/Users/arthur/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools

```

**Comment by mirandadam** [comment]
@elpaso, I totally agree. Simpler is better. Please disregard PR #29 untill I get time to rewrite that part of the code without inspect, hopefully before Brazil's game today.

**Comment by mirandadam** [comment]
Done. Please check PR #30. I believe in that case the semantics of the statement involving "inspect" is equivalent to the "__file__" automatic variable.
Now, back to the game! No goals so far. Mexico will put up a fight!

**Comment by mirandadam** [comment]
@elpaso, I can confirm that the patch is in the standard plugin repository as update 2.18.

The update works on QGis 3.2 64 bit standalone install on Windows 10 Home and Windows 10 Pro. It also works on Ubuntu 16.04 with the "deb http://qgis.org/ubuntugis xenial main" repository. A regular plugin upgrade from the QGis plugin manager menu is all that is needed for the fix to work.

@arthuragone, is your problem solved? Since you reported on OSX, I would very much like to hear from you before closing this issue.
