### ISSUE TITLE
Proxy Authentication Support

### ISSUE THREAD

**Issue by ghost** [elpaso/qgis-geocoding#6]
Get "HTTP Error 407: Proxy Authentication Required" when trying to use from behind a corporate firewall.

Can Geocoding Plugin use proxy settings from main QGIS settings?

**Comment by marcobra** [comment]
I made it working with my proxy with this simple subtitutions on code of :
~/.qgis2/python/plugins/mmqgis/mmqgis_library.py

```
So, in file mmqgis_library.py please substitute 

at line 20 
import urllib  with  import urllib2

at line 175 and at line 234  substitute
xml = urllib.urlopen(url).read() with xml = urllib2.urlopen(url).read()

Then at line 1870 substitute
value = urllib.quote(row[x].strip()) with value = urllib2.quote(row[x].strip())

```
Restart qgis and try...
Marco

**Comment by enricofer** [comment]
Fix confirmed. tested with Google Maps ( With Nominating fails.... but I don't know why)
Thanks!

**Comment by marcobra** [comment]
Be sure to modify at "line 175 and at line 234"  in my  test is working with google and nominatim
HTH

**Comment by enricofer** [comment]
Ok. Now nominating goes. Fixed

----- Messaggio originale -----
Da: "marcobra" <notifications@github.com>
Inviato: ‎10/‎03/‎2015 14:35
A: "elpaso/qgis-geocoding" <qgis-geocoding@noreply.github.com>
Cc: "enrico ferreguti" <enricofer@gmail.com>
Oggetto: Re: [qgis-geocoding] Proxy Authentication Support (#6)

Be sure to modify at "line 175 and at line 234" in my test is working with google and nominatim
HTH

**Comment by cascafico** [comment]
Thanks Marco, it works!.

Qgis Brighton
Windows7

modified file: 
C:\Users\<user>\.qgis2\python\plugins\mmqgis\mmqgis_library.py

**Comment by enricofer** [comment]
I wrote a patch to support http proxy: https://github.com/elpaso/qgis-geocoding/pull/14

**Comment by elpaso** [comment]
I think this is now implemented
